import { userKratos }    from "../hooks/kratosHook";
import styles            from '../styles/Home.module.css'
import type { NextPage } from 'next'
import Head              from 'next/head'
import 'antd/dist/antd.css';
import { Layout, Menu }  from 'antd';

const {Header} = Layout;

const Home: NextPage = () => {

  const {session, logoutUrl, loading, error} = userKratos()

  const head = <Head>
    <title>NTSprint Authentication</title>
    <meta name="description" content="Generated by create next app using Ory Kratos for authentication"/>
    <link rel="icon" href="/favicon.ico"/>
  </Head>

  if (loading) {
    return (
      <main className={styles.main}>
        {head}
        <h2>Loading...</h2>
      </main>
    )
  }

  let menuItem = []

  if (session) {
    menuItem = [
      {key: "Update your settings", label: <a href='/api/.ory/self-service/settings/browser'>Update your settings</a>},
      {key: "sign out!", label: <a data-testid="logout" href={logoutUrl} aria-disabled={!logoutUrl}>Sign Out!</a>},
    ]
  } else {
    menuItem = [
      {key: "Sign Up", label: <a href='/api/.ory/self-service/registration/browser'>Sign Up</a>},
      {key: "Sign In", label: <a href={'/api/.ory/self-service/login/browser'}>Sign In</a>},
      {key: "Recover your account", label: <a href={'/api/.ory/self-service/recovery/browser'}>Recover your account</a>},
      {key: "Verify your Email", label: <a href={'/api/.ory/self-service/verification/browser'}>Verify your Email</a>},
    ]
  }

  return (
    <>
      {head}
      <Header>
        <Menu
          theme="dark"
          mode="horizontal"
          items={menuItem}
          style={{justifyContent: "end"}}
        />
      </Header>

      <main className={styles.main}>
        <img src="https://ntsprint.com/wp-content/uploads/2019/11/Logotipo.png" alt="W3Schools.com"/>

        <h3 className={styles.title}>
          {session ? <span>You are signed in, using <a href="https://www.ory.sh/">Ory!</a></span>
            : <div>
              <div>NTSprint Test Authentication using {' '}</div>
              <div><a href="https://reactjs.org/docs/hooks-intro.html">React Hooks</a>,</div>
              <div><a href="https://ant.design/">Ant Design</a>,</div>
              <div>and <a href="https://www.ory.sh/">Ory</a>!</div>
            </div>}
        </h3>

        {session && <div className={styles.session}>
          <p>Find your session details below. </p>
          <pre className={styles.pre + ' ' + styles.code}>
                <code data-testid={'session-content'}>
                  {JSON.stringify(session, null, 2)}
                </code>
              </pre>
        </div>}
      </main>
    </>
  )
}

export default Home